### ISSUE TITLE
WP 3.2 compatibility

### ISSUE THREAD

**Issue by mattwiebe** [Gipetto/wordpress.tmbundle#15]
The Cmd+Shift+Opt+H shortcut to look up WP functions is something I do all day, every day. Obviously needs updating for WP 3.2.

I have no idea how you build this. Anything I can do to help?

**Comment by Gipetto** [comment]
Yeah, I need to get around to updating for 3.2. I've been working on a new code scraping scheme that better parses objects and stand-alone functions but it still needs some polish.

I got a new job recently and I'm not working directly with WordPress any more, so there's gonna be less focus on new features in the future. The plugin back end is written entirely in Ruby and the code scraping is currently a pretty janky PHP script that uses grep as a base for pulling function names, filters, actions and constants out of the WordPress code base.

I'm gonna see if I can get the function list updated over the weekend.

**Comment by mattwiebe** [comment]
Great, thanks for the quick reply. Looking forward to the update.

**Comment by Gipetto** [comment]
All-righty. It has been updated. Check it out and let me know what bugs you find. Behavior changes slightly:
- matches should be better because they're now scoped to either `$object->method()` search or just `function()` search
- multiple matches pop an inline menu to select the method you're actually after
- display of function definitions contains the expanded function documentation from the code itself. [See here for an example](http://top-frog.com/2011/07/11/wordpress-textmate-bundle-updated-for-wordpress-3-2/)

**Comment by mattwiebe** [comment]
You sir, are awesome. Cheers. :)
